booking/authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('join/', authapp.join, name='join'),  # sign up page url
    path('login/', authapp.login, name='login'),  # sign in page url
    path('logout/', authapp.logout, name='logout'),  # sign in page url
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify')  # user's account verification
]

booking/booking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include("authapp.urls", namespace="auth")),
    path('management/', include("adminapp.urls", namespace="management")),
    path('constructor/', include("constructor_app.urls", namespace="constructor")),
    path('support/', include("supportapp.urls", namespace="support"))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

booking/mainapp/urls.py
from django.urls import path
from mainapp import views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.main_page, name='main'),
    path('404/', mainapp.error_404, name='404'),
]

booking/media/projects/template1/template1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace="main")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

booking/supportapp/urls.py
from django.urls import path
from supportapp import views as supportapp

app_name = 'supportapp'

urlpatterns=[
    path('problem/', supportapp.new_problem, name="problem")
]

booking/supportapp/models.py
from django.db import models

# Create your models here.
from authapp.models import User


class Problem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    problem = models.CharField(max_length=1000)
    page = models.CharField(max_length=1000)

    def __str__(self):
        return self.problem


class RequestException(models.Model):
    page = models.CharField(max_length=200)
    exception_text = models.CharField(max_length=1000)
    status_code = models.PositiveIntegerField()
    time = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.exception_text

booking/supportapp/forms.py
from django import forms

from supportapp.models import Problem


class ProblemForm(forms.ModelForm):
    class Meta:
        model = Problem
        fields = ('problem', 'page')

booking/supportapp/views.py
from django.shortcuts import render, redirect

# Create your views here.
from supportapp.forms import ProblemForm


def new_problem(request):
    if request.method == 'POST':
        form = ProblemForm(request.POST)
        obj = form.save()
        obj.user = request.user
        obj.save()

        return redirect('main:main')
    else:
        form = ProblemForm()

    return render(request, 'supportapp/newproblem.html', {'form': form})

booking/supportapp/templates/supportapp/newproblem.html
{% extends 'mainapp/base.html' %}

{% block header %}
    <header role="banner" class="header-light">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'mainapp:main' %}">Book.com</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05"
                        aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarsExample05">
                    <ul class="navbar-nav ml-auto pl-lg-5 pl-0">
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'mainapp:main' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Booking Engine</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">{% if not user.is_authenticated %}
                                Login
                                {% else %}
                                {{user.name}}
                                {% endif %}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdown04">
                                {% if not user.is_authenticated %}
                                <a class="dropdown-item" href="{% url 'auth:login' %}">Sign in</a>
                                <a class="dropdown-item" href="{% url 'auth:join' %}">Sign up</a>
                                {% else %}
                                <a class="dropdown-item" href="{% url 'auth:logout' %}">Logout</a>
                                <a class="dropdown-item" href="{% url 'management:main' %}">Manage Your Hotels</a>
                                {% endif %}
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Contact</a>
                        </li>
                    </ul>


                </div>
            </div>
        </nav>
    </header>
{% endblock %}

{% block container %}
    <section class="section  py-5" style='margin-bottom:100px;'>
        <div class="container">
            <form action="{% url 'support:problem' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Submit" id="submit">
            </form>
        </div>
    </section>
{% endblock %}