booking/authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('join/', authapp.join, name='join'),  # sign up page url
    path('login/', authapp.login, name='login'),  # sign in page url
    path('logout/', authapp.logout, name='logout'),  # sign in page url
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify')  # user's account verification
]

booking/booking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include("authapp.urls", namespace="auth")),
    path('management/', include("adminapp.urls", namespace="management")),
    path('constructor/', include("constructor_app.urls", namespace="constructor")),
    path('support/', include("supportapp.urls", namespace="support"))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

booking/mainapp/urls.py
from django.urls import path
from mainapp import views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.main_page, name='main'),
    path('404/', mainapp.error_404, name='404'),
]

booking/media/projects/template1/template1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace="main")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

booking/authapp/forms.py
import hashlib
import random
from django import forms
from django.contrib.auth.forms import AuthenticationForm, \
    ReadOnlyPasswordHashField
from authapp.models import User, UserProfile, UserActivation, UserSending


class UserAdminCreationForm(forms.ModelForm):
    # Форма для создания новых пользователей.
    # Включает в себя все необходимые поля плюс повторный пароль.
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Подтвердите пароль',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'name', 'surname', 'phone_number', 'country',
                  'company_name')

    def clean_password2(self):
        # Проверка, что две записи пароля совпадают.
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Пароли не совпадают!")
        return password2

    def save(self, commit=True):
        # Сохранение пароля в хешированном формате.
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """
    Форма для обновления пользователей.
    Включает в себя все поля пользователя, но заменяет поле редактирования
    пароля на поле чтения.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'name', 'surname', 'phone_number', 'country',
                  'company_name', 'is_sending')

    def clean_password(self):
        return self.initial["password"]


class UserRegisterForm(forms.ModelForm):
    # Форма для регистрации.
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Подтвердите пароль',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'name', 'surname', 'phone_number', 'country',
                  'company_name', 'is_sending')

    def clean_password2(self):
        # Проверка, что две записи пароля совпадают.
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Пароли не совпадают!")
        return password2

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_sending':
                self.fields[field_name].label = ''
                self.fields[field_name].widget.attrs.update(
                    {'class': 'registration-form-input'})

        self.fields['email'].widget.attrs.update(
            {
                'type': 'email',
                'placeholder': 'Enter email'
            }
        )
        self.fields['password1'].widget.attrs.update(
            {
                'type': 'password',
                'placeholder': 'Password'
            }
        )

        self.fields['name'].widget.attrs.update(
            {
                'type': 'text',
                'placeholder': 'First name'
            }
        )

        self.fields['country'].widget.attrs.update(
            {
                'type': 'text',
                'placeholder': 'Your country'
            }
        )

        self.fields['company_name'].widget.attrs.update(
            {
                'type': 'text',
                'placeholder': 'Create an organization name'
            }
        )

        self.fields['surname'].widget.attrs.update(
            {
                'type': 'text',
                'placeholder': 'Last name'
            }
        )

        self.fields['phone_number'].widget.attrs.update(
            {
                'type': 'text',
                'placeholder': 'Phone number'
            }
        )

        self.fields['password2'].widget.attrs.update(
            {
                'type': 'password',
                'placeholder': 'Repeat password'
            }
        )
        self.fields['is_sending'].widget.attrs.update(
            {
                'type': 'checkbox',
                'class': 'sending_checkbox'
            }
        )

    def save(self, commit=True):
        # Сохранение пароля в хешированном формате.
        user = super(UserRegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        # Авторизация через email
        user.active = False
        salt = hashlib.sha1(str(random.random()).encode('utf8')).hexdigest()[:6]
        user_activation = UserActivation()
        user_activation.user = user
        user_activation.activation_key = hashlib.sha1((user.email + salt)
                                                      .encode('utf8')) \
            .hexdigest()

        user_activation.save()
        print(user_activation)
        print(user.active)
        print(user_activation.user)
        print(user_activation.user.active)
        return user


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'edit-form-input'
            field.help_text = ''


class UserProfileEditForm(forms.ModelForm):
    avatar = forms.ImageField(label=('Фото'), required=False,
                              widget=forms.FileInput)

    class Meta:
        model = UserProfile
        fields = ('bank_name',  'jur_form', 'avatar',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'edit-form-input'
        self.fields['avatar'].widget.attrs['class'] = 'edit-form-file'


class UserLoginForm(AuthenticationForm):
    # Форма для авторизации.
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            self.fields[field_name].label = ''

        self.fields['username'].widget.attrs.update(
            {
                'type': 'text',
                'class': 'registration-form-input',
                'placeholder': 'Email'
            }
        )
        self.fields['password'].widget.attrs.update(
            {
                'type': 'password',
                'class': 'registration-form-input',
                'placeholder': 'Пароль'
            }
        )


class UserSendingForm(forms.ModelForm):
    # Форма для рассылки.

    class Meta:
        model = UserSending
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'edit-form-input'
            self.fields[field_name].label = ''
            field.help_text = ''

        self.fields['email'].widget.attrs.update(
            {
                'type': 'text',
                'placeholder': 'Email'
            }
        )

booking/authapp/views.py
import os

from django.contrib import auth
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse
from authapp.forms import UserRegisterForm, UserLoginForm
from authapp.models import UserActivation, User

from django.conf import settings

from authapp.variables import country_dict


def join(request):
    title = 'Register'
    countries = country_dict
    if request.method == 'POST':
        register_form = UserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            user = register_form.save()
            if send_verify_mail(user):
                print('Account Verification letter has been sent!')
            else:
                print('Failed to send account verification letter')

            return HttpResponseRedirect(reverse('main:main'))
    else:
        register_form = UserRegisterForm()

    content = {'register_form': register_form,
               'countries': countries,
               'title': title,
               }

    return render(request, 'authapp/sign_up.html', content)


def login(request):
    login_form = UserLoginForm(data=request.POST)


    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user and user.active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main:main'))
    else:
        login_form = UserLoginForm()

    content = {'login_form': login_form}
    return render(request, 'authapp/sign_in.html', content)


def send_verify_mail(user):
    title = 'Account Verification {} {}'.format(user.name, user.surname)

    html_m = render_to_string('authapp/letter.html',
                              {'user': user, 'domain': settings.DOMAIN_NAME,
                               'activation_key': UserActivation.objects.get(user=user).activation_key}
                              )

    return send_mail(title, '', settings.EMAIL_HOST_USER,
                     [user.email], html_message=html_m, fail_silently=False)


def verify(request, email, activation_key):
    try:
        user = User.objects.get(email=email)
        user_activation = UserActivation.objects.get(user=user)

        if user_activation.activation_key == activation_key and not user_activation.is_activation_key_expired():
            print('activating...')
            user.active = True
            user.save()
            auth.login(request, user)
            print(f'successfully activated user: {user}')
        else:
            print(f'error activation user: {user}')

        return HttpResponseRedirect(reverse('main:main'))

    except Exception as e:
        print(f'error activation user : {e.args}')
        return HttpResponseRedirect(reverse('main:main'))



def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:main'))

booking/authapp/templates/authapp/letter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <title>Title</title>
    <style>
        body {
            /*background-color: #f9f9f9;*/
        }

        .content {
            margin: 0;
            padding: 0;
            background-color: white;
        }

        table {
            border-collapse: collapse;
        }


        .content {
            margin: auto;
        }

        @media (max-width: 480px) {
            .content {
                width: 100%;
            }
        }

        @media (min-width: 481px) {
            .content {
                width: 70%;
            }
        }

        .header {
            /*background-color: #b43de2;*/
            color: white;
        }

        .font {
            font-family: Gotham SSm A, Gotham SSm B, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Droid Sans, Helvetica Neue, Arial, sans-serif;
            font-weight: 700;
            font-size: 25px;
            margin-left: 7px;
        }

        /*.btn {*/
        /*    background-color: #b43de2;*/
        /*    color: white;*/
        /*}*/
        p {
            margin-left: 7px;
        }
    </style>
</head>
<body>
<table class="content">
    <tbody>
    <tr>
        <td align="center">
            <table style="width: 100%" class="header">
                <tr>
                    <td><p class="font" style="height:20px">Leiden - Verify account</p></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <p class="font">Hello, {{ user.name }}!</p>
        </td>
    </tr>
    <tr>
        <td>
            <p class="message">
                Thank you, for creating an account in Leiden.ru <br>
                Please, verify your account.
                <br>
            </p>
            <a href="http://{{ domain }}{% url 'auth:verify' user.email activation_key %}">
                <button type="button" class="btn btn-primary">Verify</button>
            </a>
        </td>
    </tr>
    </tbody>

</table>
</body>
</html>

booking/authapp/templates/authapp/sign_in.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Book.com - Sign in</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800|DM+Serif+Display:400,400i&display=swap"
          rel="stylesheet">

    <link rel="shortcut icon" href="ftco-32x32.png">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800" rel="stylesheet">

    <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static '/css/animate.css'%}">
    <link rel="stylesheet" href="{% static '/css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static '/css/aos.css'%}">
    <link rel="stylesheet" href="{% static '/css/auth.css'%}">

    <link rel="stylesheet" href="{% static '/css/magnific-popup.css'%}">


    <link rel="stylesheet" href="{% static '/fonts/ionicons/css/ionicons.min.css'%}">
    <link rel="stylesheet" href="{% static '/fonts/fontawesome/css/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{% static '/fonts/flaticon/font/flaticon.css'%}">

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static '/css/style.css'%}">
</head>
<body>

<header role="banner">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'main:main' %}">Book.com</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05"
                    aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExample05">
                <ul class="navbar-nav ml-auto pl-lg-5 pl-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'main:main' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="recipes.html">Booking Engine</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="services.html" id="dropdown04" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">Login</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown04">
                            <a class="dropdown-item" href="{% url 'auth:login' %}">Sign in</a>
                            <a class="dropdown-item" href="{% url 'auth:join' %}">Sign up</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="about.html">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contact.html">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- END header -->
<section  style="background: url(/static/img/simple-codelines.svg), #2b3137;background-size: cover; height: 100vh; overflow: auto">
    <div class="auth">
        <form action="{% url 'authapp:login' %}" method="post" style="margin-top:100px">
            {% csrf_token %}

            <h2>Sign In</h2>
            {{ login_form.as_p }}
            {% if login_form.errors %}
            {% for error in login_form.errors %}{{error}}{% endfor %}
            {% endif %}
<!--            <p>-->
<!--                <label for="Email" class="floatLabel">Email</label>-->
<!--                <input required id="Email" name="email" type="text">-->
<!--            </p>-->
<!--            <p>-->
<!--                <label for="password" class="floatLabel">Password</label>-->
<!--                <input required id="password" name="password" type="password">-->
<!--            </p>-->
            <p>
                <input type="submit" value="Sign in for Book.com" id="submit">
            </p>
        </form>
    </div>
</section>


<footer class="site-footer" role="contentinfo">

    <div class="container">
        <div class="row mb-5">
            <div class="col-md-4 mb-5">
                <h3>About Us</h3>
                <p class="mb-5">Book.com is an all in one booking and accommodation management system for small hotels,
                    guesthouses and B&B’s.
                    <br>
                    With Little Hotelier, small accommodation providers level the playing field, increase occupancy and
                    drive revenue.</p>
                <ul class="list-unstyled footer-link d-flex footer-social">
                    <li><a href="#" class="p-2"><span class="fa fa-twitter"></span></a></li>
                    <li><a href="#" class="p-2"><span class="fa fa-facebook"></span></a></li>
                    <li><a href="#" class="p-2"><span class="fa fa-linkedin"></span></a></li>
                    <li><a href="#" class="p-2"><span class="fa fa-instagram"></span></a></li>
                </ul>

            </div>
            <div class="col-md-5 mb-5">
                <div class="mb-5">
                    <h3>Opening Hours</h3>
                    <p><strong class="d-block font-weight-normal text-black">Monday-Friday</strong>9AM-9PM</p>
                </div>
                <div>
                    <h3>Contact Info</h3>
                    <ul class="list-unstyled footer-link">
                        <li class="d-block">
                            <span class="d-block text-black">Address:</span>
                            <span>c. Moscow, 34 ylitsa Lenina</span></li>
                        <li class="d-block"><span class="d-block text-black">Phone:</span><span>+1 242 4942 290</span>
                        </li>
                        <li class="d-block"><span
                                class="d-block text-black">Email:</span><span>info@yourdomain.com</span></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3 mb-5">
                <h3>Quick Links</h3>
                <ul class="list-unstyled footer-link">
                    <li><a href="#">About</a></li>
                    <li><a href="#">Terms of Use</a></li>
                    <li><a href="#">Disclaimers</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>
            <div class="col-md-3">

            </div>
        </div>
        <div class="row">
            <div class="col-12 text-md-center text-left">
               <!--  <p>

                </p> -->
            </div>
        </div>
    </div>
</footer>
<!-- END footer -->
<!-- END footer -->
<script src="/static/js/sign_up.js"></script>
<script src="{% static '/js/jquery-3.2.1.min.js'%}"></script>
<script src="{% static '/js/popper.min.js'%}"></script>
<script src="{% static '/js/bootstrap.min.js'%}"></script>
<script src="{% static '/js/owl.carousel.min.js'%}"></script>
<script src="{% static '/js/jquery.waypoints.min.js'%}"></script>
<script src="{% static '/js/aos.js'%}"></script>

<script src="{% static '/js/jquery.magnific-popup.min.js'%}"></script>
<script src="{% static '/js/magnific-popup-options.js'%}"></script>


<script src="{% static '/js/main.js'%}"></script>
</body>
</html>

booking/authapp/templates/authapp/sign_up.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Book.com - Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800|DM+Serif+Display:400,400i&display=swap"
          rel="stylesheet">

    <link rel="shortcut icon" href="ftco-32x32.png">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800" rel="stylesheet">

    <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static '/css/animate.css'%}">
    <link rel="stylesheet" href="{% static '/css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static '/css/aos.css'%}">
    <link rel="stylesheet" href="{% static '/css/auth.css'%}">

    <link rel="stylesheet" href="{% static '/css/magnific-popup.css'%}">


    <link rel="stylesheet" href="{% static '/fonts/ionicons/css/ionicons.min.css'%}">
    <link rel="stylesheet" href="{% static '/fonts/fontawesome/css/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{% static '/fonts/flaticon/font/flaticon.css'%}">

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static '/css/style.css'%}">
</head>
<body>

<header role="banner">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'main:main' %}">Book.com</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05"
                    aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExample05">
                <ul class="navbar-nav ml-auto pl-lg-5 pl-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'main:main' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Booking Engine</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">Login</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown04">
                            <a class="dropdown-item" href="{% url 'authapp:login'  %}">Sign in</a>
                            <a class="dropdown-item" href="{% url 'authapp:join'  %}">Sign up</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- END header -->
<section style="background: url(/static/img/simple-codelines.svg), #2b3137;background-size: cover; height: 110vh; overflow: auto">
    <div class="auth">
        <form action="#" method="post" style="margin-top:100px">
            <h2>Sign Up</h2>
            <!--            <p>-->
            <!--                <label for="name" class="floatLabel">First name</label>-->
            <!--                <input required id="name" name="name" type="text">-->
            <!--            </p>-->
            <!--            <p>-->
            <!--                <label for="surname" class="floatLabel">Last name</label>-->
            <!--                <input required id="surname" name="surname" type="text">-->
            <!--            </p>-->
            <!--            <p>-->
            <!--                <label for="property_name" class="floatLabel">Property/Company name</label>-->
            <!--                <input required id="property_name" name="property_name" type="text">-->
            <!--            </p>-->
            <!--            <p>-->
            <!--                <label for="number" class="floatLabel">Phone number</label>-->
            <!--                <input required id="number" name="number" type="text">-->
            <!--            </p>-->
            <!--            <p>-->
            <!--                <label for="Email" class="floatLabel">Email</label>-->
            <!--                <input required id="Email" name="email" type="text">-->
            <!--            </p>-->
            <!--            <p>-->
            <!--                <label for="password" class="floatLabel">Password</label>-->
            <!--                <input required id="password" name="password" type="password">-->
            <!--                <span>Enter a password longer than 8 characters</span>-->
            <!--            </p>-->
            <!--            <p>-->
            <!--                <label for="confirm_password" class="floatLabel">Confirm Password</label>-->
            <!--                <input required id="confirm_password" name="confirm_password" type="password">-->
            <!--                <span>Your passwords do not match</span>-->
            <!--            </p>-->

            {% csrf_token %}
            {{ register_form.as_p }}
            <p>
                <input type="submit" value="Sign up for Book.com" id="submit">
            </p>
        </form>
    </div>
</section>


<footer class="site-footer" role="contentinfo">

    <div class="container">
        <div class="row mb-5">
            <div class="col-md-4 mb-5">
                <h3>About Us</h3>
                <p class="mb-5">Book.com is an all in one booking and accommodation management system for small hotels,
                    guesthouses and B&B’s.
                    <br>
                    With Little Hotelier, small accommodation providers level the playing field, increase occupancy and
                    drive revenue.</p>
                <ul class="list-unstyled footer-link d-flex footer-social">
                    <li><a href="#" class="p-2"><span class="fa fa-twitter"></span></a></li>
                    <li><a href="#" class="p-2"><span class="fa fa-facebook"></span></a></li>
                    <li><a href="#" class="p-2"><span class="fa fa-linkedin"></span></a></li>
                    <li><a href="#" class="p-2"><span class="fa fa-instagram"></span></a></li>
                </ul>

            </div>
            <div class="col-md-5 mb-5">
                <div class="mb-5">
                    <h3>Opening Hours</h3>
                    <p><strong class="d-block font-weight-normal text-black">Monday-Friday</strong>9AM-9PM</p>
                </div>
                <div>
                    <h3>Contact Info</h3>
                    <ul class="list-unstyled footer-link">
                        <li class="d-block">
                            <span class="d-block text-black">Address:</span>
                            <span>c. Moscow, 34 ylitsa Lenina</span></li>
                        <li class="d-block"><span class="d-block text-black">Phone:</span><span>+1 242 4942 290</span>
                        </li>
                        <li class="d-block"><span
                                class="d-block text-black">Email:</span><span>info@yourdomain.com</span></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3 mb-5">
                <h3>Quick Links</h3>
                <ul class="list-unstyled footer-link">
                    <li><a href="#">About</a></li>
                    <li><a href="#">Terms of Use</a></li>
                    <li><a href="#">Disclaimers</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>
            <div class="col-md-3">

            </div>
        </div>
        <div class="row">
            <div class="col-12 text-md-center text-left">
                <p>

                </p>
            </div>
        </div>
    </div>
</footer>
<!-- END footer -->
<script src="/static/js/sign_up.js"></script>
<script src="{% static '/js/jquery-3.2.1.min.js'%}"></script>
<script src="{% static '/js/popper.min.js'%}"></script>
<script src="{% static '/js/bootstrap.min.js'%}"></script>
<script src="{% static '/js/owl.carousel.min.js'%}"></script>
<script src="{% static '/js/jquery.waypoints.min.js'%}"></script>
<script src="{% static '/js/aos.js'%}"></script>

<script src="{% static '/js/jquery.magnific-popup.min.js'%}"></script>
<script src="{% static '/js/magnific-popup-options.js'%}"></script>

<script src="{% static '/js/form.js' %}"></script>

<script src="{% static '/js/main.js'%}"></script>
</body>
</html>