booking/authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('join/', authapp.join, name='join'),  # sign up page url
    path('login/', authapp.login, name='login'),  # sign in page url
    path('logout/', authapp.logout, name='logout'),  # sign in page url
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify')  # user's account verification
]

booking/booking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include("authapp.urls", namespace="auth")),
    path('management/', include("adminapp.urls", namespace="management")),
    path('constructor/', include("constructor_app.urls", namespace="constructor")),
    path('support/', include("supportapp.urls", namespace="support"))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

booking/constructor_app/urls.py
from django.urls import path
from constructor_app import views as constructor

app_name = 'constructor_app'

urlpatterns = [
    path('', constructor.main, name='main'),
    path('detail/template-<int:id>/', constructor.about_template, name='about_template'),
    path('pack/', constructor.pack_project, name='pack'),
    path('orders/', constructor.orders_list, name='orders_list'),
]

booking/media/projects/template1/template1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace="main")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

booking/constructor_app/models.py
import datetime

from dateutil.relativedelta import relativedelta
from django.db import models

from authapp.models import User
from mainapp.models import Hotel


class Template(models.Model):
    name = models.CharField(max_length=100, verbose_name="Template's name")
    price = models.PositiveIntegerField()
    orders = models.PositiveIntegerField(default=0)
    banner = models.ImageField(verbose_name="Template's Image")
    path = models.CharField(max_length=200, verbose_name="Path to template", default="media/projects/...")
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов'),
        (CANCEL, 'отменен'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(verbose_name='статус',
                              max_length=3,
                              choices=ORDER_STATUS_CHOICES,
                              default=FORMING)
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    template = models.ForeignKey(Template, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.name + ' ' + self.hotel.name


class WebSite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    token = models.CharField(max_length=9, null=True, unique=True)
    url = models.CharField(max_length=100, null=True, unique=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    date_of_expiry = models.DateField(default=datetime.datetime.today() + relativedelta(years=+1))
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.hotel.name

booking/constructor_app/views.py
import json
import os

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from django.template import RequestContext, engines, Context
from django.template.loader import render_to_string

import mainapp
from constructor_app import utils
from constructor_app.models import Template, Order
from mainapp.models import Hotel, HotelFacility, Room, RoomGallery

from constructor_app.models import WebSite


@login_required(login_url='/auth/login/')
def main(request):
    templates = Template.objects.all()
    hotel_id = request.GET['hotel_id']

    return render(request, 'constructor_app/main.html', {'templates': templates, 'hotel_id': hotel_id})


@login_required(login_url='/auth/login/')
def about_template(request, id):
    # get template
    template = get_object_or_404(Template, id=id)

    hotel_id = request.GET.get('hotel_id', 0)

    return render(request, 'constructor_app/detail.html', {'template': template, 'hotel_id': hotel_id})


@login_required(login_url='/auth/login/')
def orders_list(request):
    orders = Order.objects.filter(user=request.user)

    return render(request, 'constructor_app/orders.html', {'orders': orders})


@login_required(login_url='/auth/login/')
def pack_project(request):
    if request.GET.get('hotel_id', 0) and request.GET.get('template_id', 0):
        # get template
        template = get_object_or_404(Template, id=request.GET.get('template_id'))

        # create order for user
        hotel = get_object_or_404(Hotel, id=request.GET['hotel_id'])
        order = Order.objects.create(user=request.user, hotel=hotel, template=template)

        prj_path = f'{settings.BASE_DIR}/media/preparing_projects/{order.id}'  # new project path
        template_path = f'{settings.BASE_DIR}/{order.template.path}'

        # create project folder
        os.mkdir(prj_path)
        utils.copytree(template_path, prj_path)

        # copying projects to zip archive
        if order.status == Order.FORMING:
            django_engine = engines['django']
            template = django_engine.from_string(open(prj_path + '/index.html', 'r').read())

            context = {'hotel': hotel, 'domain': settings.DOMAIN_NAME,
                       'facilities': HotelFacility.objects.filter(hotel=hotel),
                       'rooms': [{'id': room.id, 'name': room.name, 'avatar': '', 'price': room.price} for room in
                                 Room.objects.filter(hotel=hotel, is_active=True)]}

            for room in context['rooms']:
                try:
                    room['avatar'] = RoomGallery.objects.get(room__id=room['id'], is_avatar=True)
                except mainapp.models.RoomGallery.DoesNotExist:
                    room['avatar'] = RoomGallery.objects.filter(room__id=room['id'])[0]

            data = template.render(context)

            # rewrite page index.html
            file = open(os.path.join(prj_path, 'index.html'), 'w')
            file.write(str(data))
            file.close()

            utils.zipdir(order.hotel.name + str(order.id), prj_path,
                         f'{settings.BASE_DIR}/media/ready_projects', order.id)

            order.status = Order.READY
            order.save()
        else:
            return redirect('main:404')

        return render(request, 'constructor_app/result.html',
                      {'order': order,
                       'path': f'{settings.DOMAIN_NAME}/media/ready_projects/{order.hotel.name}{order.id}.zip'})

booking/constructor_app/templates/constructor_app/detail.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load query_booking %}


{% block content %}
    <main>
        <div class="container-fluid">
            <div class="card mb-4" style="margin-top: 30px">
                <div class="card-header"><i class="fas fa-table mr-1"></i>Templates</div>
                <div class="card-body item-description">
                    <p class="h3">
                        {{ template.name }}
                    </p>
                    <div class="row">
                        <div class="col-sm-12 col-md-8 col-lg-8">
                            <img src="{{ template.banner.url }}" alt="{{ template.name }}">
                        </div>
                        <div class="col-sm-12 col-md-4 col-lg-4">
                            <p class="h3">Description</p>
                            <span class="h5">
                                {{ template.description }}
                            </span>
                            <br>
                            <span class="h3">
                                <strong>{{ template.price }}$</strong>
                            </span>
                            <br>
                            <button type="button" style="margin-top: 20px" class="btn btn-outline-primary">
                                {% if hotel_id and template.id %}
                                    <a href="{% url 'constructor:pack' %}?hotel_id={{ hotel_id }}&template_id={{ template.id }}" class="hover-white">Buy</a>
                                {% else %}
                                    Unavailable to create project
                                {% endif %}
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

booking/constructor_app/templates/constructor_app/main.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load query_booking %}
{% load truncate_text %}


{% block content %}
    <main>
        <div class="container-fluid">
            <div class="card mb-4" style="margin-top: 30px">
                <div class="card-header"><i class="fas fa-table mr-1"></i>Templates</div>
                <div class="card-body">
                    <div class="row">
                        {% for template in templates %}
                            <div class="col-sm-12 col-md-4 col-lg-4" style="margin-top: 10px; margin-bottom: 10px">
                                <div class="list-item">
                                    <p class="h3">
                                        {{ template.name }}.
                                    </p>
                                    <img src="{{ template.banner.url }}" style="width: 100%" alt="{{ template.name }}">
                                    <p class="h5">
                                        {{ template.description|truncate_text }}
                                    </p>
                                    <p class="h4">
                                        <strong>{{ template.price }}$</strong>
                                    </p>
                                    <button type="button" class="btn btn-outline-primary">
                                        <a href="{% url 'constructor:about_template' template.id %}?hotel_id={{ hotel_id }}" class="hover-white">Buy</a>
                                    </button>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

booking/constructor_app/templates/constructor_app/orders.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load query_booking %}
{% load truncate_text %}


{% block content %}
    <main>
        <div class="container-fluid">
            <div class="card mb-4" style="margin-top: 30px">
                <div class="card-header"><i class="fas fa-table mr-1"></i>Orders</div>
                <div class="card-body">
                    <div class="row">
                        {% for order in orders %}
                            <div class="col-sm-12 col-md-4 col-lg-4" style="margin-top: 10px; margin-bottom: 10px">
                                <div class="list-item">
                                    <p class="h3">
                                        {{ order.hotel.name }} -

                                        {% if order.status == order.FORMING  %}
                                            forming
                                        {% elif order.status == order.READY %}
                                            completed
                                        {% else %}
                                        {% endif %}
                                    </p>
                                    <p class="h5">
                                        {{ order.template.description|truncate_text }}
                                    </p>
                                    <p class="h4">
                                        <a href="{% url 'constructor:about_template' order.template.id %}">{{ order.template.name }}</a>
                                        <strong>{{ order.template.price }}$</strong>
                                    </p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

booking/constructor_app/templates/constructor_app/result.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load query_booking %}


{% block content %}
    <main>
        <div class="container-fluid">
            <div class="card mb-4" style="margin-top: 30px">
                <div class="card-header"><i class="fas fa-table mr-1"></i>Templates</div>
                <div class="card-body item-description">
                    <p class="h3">
                        You have successfully created web site for your hotel: {{ order.hotel.name }}.
                    </p>
                    <p class="h4">
                        <strong>Pay: {{ order.template.price }}$</strong>
                    </p>
                    <p class="h5">
                        Download project <a href="http://{{ path }}"> here</a>
                    </p>

                </div>
            </div>
        </div>
    </main>
{% endblock %}