booking/adminapp/urls.py
from django.urls import path
from adminapp import views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('main/', adminapp.main, name='main'),
    path('create_hotel/', adminapp.create_hotel, name='create_hotel'),
    path('create_room/', adminapp.create_room, name='create_room'),
    path('hotels/', adminapp.hotels, name='hotels'),
    path('rooms/', adminapp.rooms, name='rooms'),
    path('hotel-<int:pk>/edit_hotel/', adminapp.edit_hotel, name="edit_hotel"),
    path('hotel-<int:hotel_id>/room-<int:room_id>/edit_room/', adminapp.edit_room, name="edit_room"),
    path('room-<int:id>/delete/', adminapp.delete_room, name="delete_room"),
    path('hotel-<int:id>/delete/', adminapp.delete_hotel, name="delete_hotel"),
    # ajax
    path('ajax/check_address/', adminapp.ajax_check_address, name="ajax_check_address"),
    path('ajax/delete_image/', adminapp.ajax_delete_image, name="ajax_delete_image"),
    path('ajax/get_rooms/', adminapp.ajax_get_rooms, name="ajax_get_rooms"),

]

booking/authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('join/', authapp.join, name='join'),  # sign up page url
    path('login/', authapp.login, name='login'),  # sign in page url
    path('logout/', authapp.logout, name='logout'),  # sign in page url
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify')  # user's account verification
]

booking/booking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include("authapp.urls", namespace="auth")),
    path('management/', include("adminapp.urls", namespace="management")),
    path('constructor/', include("constructor_app.urls", namespace="constructor")),
    path('support/', include("supportapp.urls", namespace="support"))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

booking/media/projects/template1/template1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace="main")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

booking/adminapp/models.py
# from django.db import models

# Create your models here.

booking/mainapp/models.py
import datetime
import os
from uuid import uuid4

from django.db import models
from django.db.models import Q
from django.utils.deconstruct import deconstructible

from authapp.models import User
from authapp.variables import country_dict
from mainapp.variables import arrival_time


@deconstructible
class PathAndRename(object):

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        filename = '{}.{}'.format(uuid4().hex, ext)

        return os.path.join(self.path, filename)


path_and_rename = PathAndRename("rooms/")


class Hotel(models.Model):
    class Meta:
        verbose_name = 'Отель'
        verbose_name_plural = 'Отели'
        ordering = ['name']

    ONE = 'ON'
    TWO = 'TW'
    THREE = 'TR'
    FOUR = 'FR'
    FIVE = 'FV'
    STARS_CHOICES = [
        (ONE, '1*'),
        (TWO, '2*'),
        (THREE, '3*'),
        (FOUR, '4*'),
        (FIVE, '5*'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, default='')
    name = models.CharField(verbose_name='Название отеля', max_length=64)
    phone_number = models.CharField(verbose_name='Номер телефона', default='',
                                    max_length=20)
    location = models.CharField(verbose_name='Адрес отеля', default='',
                                max_length=200)
    description = models.TextField(verbose_name='Описание отеля', blank=True)
    stars = models.CharField(max_length=2, choices=STARS_CHOICES, default=ONE)
    banner = models.ImageField(default='', upload_to='hotels/banners/')
    is_active = models.BooleanField(verbose_name='Активен', default=True)

    def __str__(self):
        return self.name

    def get_count_facility(self):
        items = self.hotelfacility.select_related()
        return len(items)

    def get_facility(self):
        arr = []
        items = self.hotelfacility.select_related()
        for i in range(len(items)):
            arr.append(items[i].get_name())
        return arr

    def get_facility_icon(self):
        arr = []
        items = self.hotelfacility.select_related()
        for i in range(len(items)):
            arr.append(items[i].get_icon())
        return arr


class Facility(models.Model):
    class Meta:
        verbose_name = 'Facility'
        verbose_name_plural = 'Facilities'

    # icon = models.ImageField(default='', upload_to='hotels/icons/')
    icon = models.ImageField(upload_to=path_and_rename,
                             verbose_name='Facility icon')
    name = models.CharField(verbose_name='Facility', max_length=64,
                            unique=True)

    @staticmethod
    def get_items():
        return Facility.objects.all().order_by('name')

    def __str__(self):
        return self.name


class HotelFacility(models.Model):
    class Meta:
        verbose_name = ' Hotel Facility'
        verbose_name_plural = 'Hotel Facilities'

    hotel = models.ForeignKey(Hotel, related_name="facility",
                              on_delete=models.CASCADE)
    facility = models.ForeignKey(Facility, verbose_name='Facility name',
                                 on_delete=models.CASCADE)

    def get_icon(self):
        return self.facility.icon

    def get_name(self):
        return self.facility.name

    @staticmethod
    def get_items():
        return HotelFacility.objects.all().order_by('facility')

    def __str__(self):
        return self.facility.name


class RoomAgent(models.Model):
    class Meta:
        verbose_name = 'Агент'
        verbose_name_plural = 'Агенты'
        ordering = ['name']

    name = models.CharField(verbose_name='Имя агента', max_length=64,
                            unique=True)
    description = models.CharField(verbose_name='Краткое описание агента',
                                   max_length=128, blank=True)
    is_active = models.BooleanField(verbose_name='Активен', default=True)

    def __str__(self):
        return self.name


class RoomManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (
                    Q(name__icontains=query) |
                    Q(description__icontains=query)
            )
            # distinct() is often necessary with Q lookups
            qs = qs.filter(or_lookup).distinct()
        return qs


class Room(models.Model):
    class Meta:
        verbose_name = 'Номер'
        verbose_name_plural = 'Номера'
        ordering = ['name']

    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, default='')
    name = models.CharField(verbose_name='Имя', max_length=32)
    price = models.DecimalField(verbose_name='Цена', max_digits=12,
                                decimal_places=2, default=0)
    description = models.TextField(verbose_name='Описание', blank=True)
    adult = models.PositiveIntegerField(verbose_name='Взрослый', default=0)
    kids = models.PositiveIntegerField(verbose_name='Детский', default=0)
    infants = models.PositiveIntegerField(verbose_name='Детский', default=0)
    # image = models.ImageField(upload_to=path_and_rename, blank=True)
    is_active = models.BooleanField(verbose_name='Номер активен', default=True)

    objects = RoomManager()

    def __str__(self):
        return "{} ({})".format(self.name, self.hotel.name)

    def __unicode__(self):
        return self.name


class RoomGallery(models.Model):
    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'
        ordering = ['image']

    room = models.ForeignKey(Room, on_delete=models.CASCADE,
                             verbose_name='Название номера')
    image = models.ImageField(upload_to=path_and_rename,
                              verbose_name='Изображение номера')
    is_avatar = models.BooleanField(verbose_name='Главное изображение номера', default=False)

    def __str__(self):
        return self.room.name


# def make_avatar(args*):


class Bookings(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, default='')
    date = models.DateField()  # date of booking
    room = models.ForeignKey(Room, on_delete=models.CASCADE)  # room which we are trying to book
    client_name = models.CharField(max_length=100)
    client_email = models.CharField(max_length=100)  # client's email
    phone_number = models.CharField(max_length=20,  verbose_name="Client's phone number")
    time = models.CharField(max_length=50, choices=arrival_time,
                            default='12:00')  # approximate time of check in
    comments = models.CharField(max_length=500)  # client's requests
    country = models.CharField(max_length=50, choices=country_dict,
                               default='Russia')
    address = models.CharField(max_length=100)  # client's address of living

    def __str__(self):
        return 'Room Booking {} - {}'.format(self.room.name, self.room.hotel.name)


class Comment(models.Model):
    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['author']

    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    author = models.CharField(verbose_name='Author', max_length=32)
    comment = models.CharField(verbose_name='comment', max_length=200)
    rate = models.PositiveIntegerField()
    pub_date = models.DateField(verbose_name='создан', default=datetime.date.today)

    def __str__(self):
        return self.author

booking/adminapp/forms.py
from django import forms

from mainapp.models import Hotel, Room, Facility


class HotelForm(forms.ModelForm):
    class Meta:
        model = Hotel
        fields = ('name', 'description', 'stars', 'location', 'banner', 'is_active',)
        widgets = {
            'description': forms.Textarea(attrs={'rows': 3, 'cols': 15}),
        }


class FacilityForm(forms.ModelForm):

    class Meta:
        model = Facility
        fields = '__all__'
        # exclude = ()

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.fields['facility'].queryset = Facility.get_items().select_related()
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class NameModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return "%s" % obj.name


class HotelFacilityForm(forms.Form):
    CHOICES = (
        ('y', u"yes"),
        ('n', u"no"),
    )
    hotel = NameModelChoiceField(label=u'Hotel', queryset=Hotel.objects.order_by('-name'))  # , initial=Hotel.objects.get(id=1)
    bar = forms.ChoiceField(label=u'<fh', choices=CHOICES)
    pool = forms.ChoiceField(label=u'<fh', choices=CHOICES)
    wifi = forms.ChoiceField(label=u'<fh', choices=CHOICES)
    parking = forms.ChoiceField(label=u'<fh', choices=CHOICES)
    facil = NameModelChoiceField(label=u'Удобства',
                                 queryset=Facility.objects.order_by('-name'), initial=Facility.objects.all())  # get(id=1)


# class HotelFacilityForm(forms.ModelForm):
#
#     class Meta:
#         model = HotelFacility
#         fields = '__all__'
#         # exclude = ()
#
#     def __init__(self, **kwargs):
#         super().__init__(**kwargs)
#         # self.fields['facility'].queryset = HotelFacility.get_items().select_related()
#         for field_name, field in self.fields.items():
#             field.widget.attrs['class'] = 'form-control'


class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ('name', 'price', 'description', 'adult', 'kids', 'infants',
                  'is_active')

        widgets = {
            'description': forms.Textarea(attrs={'rows': 3, 'cols': 15}),
        }

booking/adminapp/templates/adminapp/edit_hotel.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load query_booking %}
{% load truncate_text %}


{% block content %}
    <main>
        <div class="container-fluid">
            <div class="container">
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>
                                {{ message }}
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>

            <form action="{% url 'management:edit_hotel' pk %}" id="edit_form" style="margin-bottom: 20px" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Edit Hotel"/>
            </form>
        </div>
    </main>
{% endblock %}
{% block jquery %}
    <script>
        let locationCheck = false;
        $("#id_location").blur(function () {
            console.log($(this).val());

            $.ajax({
                url: '/management/ajax/check_address/',
                data: {'address': $(this).val()},
                dataType: 'json',
                success: function (data) {
                    if (data.coordinates.length) {
                        $("#id_location").css({'border-color': 'green'});

                        $("#form-message").html(`
                        <div class="form-message-success">
                            <h5>
                                ${data.address}
                            </h5>
                            <h5>
                                ${data.coordinates}
                            </h5>
                        </div>
                    `);
                        locationCheck = true;
                    }
                },
                error: function () {
                    $("#id_location").css({'border-color': 'red'});
                    locationCheck = false;
                }
            });

        })
    </script>
{% endblock %}

booking/adminapp/templates/adminapp/edit_room.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load query_booking %}
{% load file_name %}


{% block content %}
    <main>
        <div class="container-fluid">
            <div class="container">
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>
                                {{ message }}
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>

            <form action="{% url 'management:edit_room' hotel_id room_id %}" id="edit_form" style="margin-bottom: 20px"
                  method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}

                <label>Edit Images</label>
                <div class="form_images">
                    {% for image in images %}
                        <div class="form_image_container" id="{{ room.hotel.pk }}-{{ room.pk }}-{{ image.image.url|file_name:'/media/rooms/' }}">
                            <img src="{{ image.image.url }}" class="form_image" alt="{{ room.name }}">
                            <div class="overlay">
                                <a href="javascript:void(0)" class="delete_image" data-room="{{ room.pk }}"
                                    data-hotel="{{ room.hotel.pk }}"
                                    data-image="{{ image.image.url|file_name:'/media/rooms/' }}"><i
                                        class="fa fa-trash icon" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    {% endfor %}

                </div>

                <label>Add Images</label>
                <div id="image_inputs" style="text-align: center">
                    <div class="field_row" v-bind:id="num" v-for="num in fields_count">
                        <input type="file" required id="image" v-bind:name="num">
                        <a href="#" v-bind:id="num" v-on:click="delete_field"><i class="fa fa-trash"
                                                                                 aria-hidden="true"></i></a>
                    </div>
                    <a href="#" v-on:click="addImageForm">
                        <i class="fa fa-plus" aria-hidden="true"></i>
                    </a>
                </div>


                <input type="hidden" id="image_count" name="image_count">

                <input type="submit" value="Edit Room"/>
            </form>
        </div>
    </main>
{% endblock %}

{% block jquery %}
    <script>
        $(document).click(function (e) {
           console.log(e.target);
        });

        $("body").on('click','.delete_image' , function () {
            let room = $(this).data('room');
            let hotel = $(this).data('hotel');
            let image = $(this).data('image');
            let el = '#'+hotel.toString()+'-'+room.toString()+'-'+image;
            console.log(el);
            let parent = $(el);
            $.ajax({
                url: '/management/ajax/delete_image/',
                data: {
                    'room': room,
                    'hotel': hotel,
                    'image': image,
                },
                dataType: 'json',
                success: function (data) {
                    console.log($(this));
                    if (data.code === 200) {
                        parent.remove();
                    } else {
                        alert('Unable to delete photo');
                    }
                },
                error: function () {
                    alert('Unable to delete photo');
                }
            });

        });
    </script>
    <script>
        const app = new Vue({
            el: '#edit_form',
            data: {
                fields_count: [],
                count: 0
            },
            methods: {
                addImageForm: function (e) {
                    this.count++;
                    this.fields_count.push(`image-${this.count}`);
                    $('#image_count').val(this.count);
                },
                checkForm: function (e) {
                    if (this.count < 3) {
                        console.log(this.count);
                        e.preventDefault();
                    }
                },
                delete_field: function (e) {
                    if (this.count > 0) {
                        console.log(e.target);
                        this.count--;
                        this.fields_count.pop();
                        $('#image_count').val(this.count);

                    }
                }
            }
        })
    </script>
{% endblock %}

booking/adminapp/templates/adminapp/hotels.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load query_booking %}
{% load truncate_text %}


{% block content %}
    <main>
        <div class="container-fluid">
            <div class="card mb-4" style="margin-top: 30px">
                <div class="card-header"><i class="fas fa-table mr-1"></i>Hotels</div>
                <div class="card-body">
                    {% for hotel in hotels %}
                        <div class="list-item">
                            <p class="h3">
                                {{ hotel.name }}.
                                <a href="{% url 'management:edit_hotel' hotel.pk %}">
                                    <i class="fas fa-pencil-alt"></i>
                                </a>
                                <a href="{% url 'management:delete_hotel' hotel.pk %}">
                                        <i class="fa fa-trash" aria-hidden="true"></i>
                                    </a>
                            </p>
                            <img src="{{ hotel.banner.url }}" alt="{{ hotel.name }}">
                            <p class="h5">
                                {{ hotel.description|truncate_text }}
                            </p>
                            <p class="h6">
                                <a href="{% url 'constructor:main' %}?hotel_id={{ hotel.id }}">Create Web Site for this hotel</a>
                            </p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </main>
{% endblock %}

booking/adminapp/templates/adminapp/main.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load query_booking %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Dashboard</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Dashboard</li>
        </ol>
        <div class="row">
            <div class="col-xl-6 col-md-6">
                <div class="card  mb-4">
                    <div class="card-body">Rooms</div>
                    <div class="card-footer d-flex align-items-center justify-content-between">
                        <a class="small stretched-link" href="{% url 'management:rooms' %}">Your rooms
                            - {{ rooms|length }}</a>
                        <div class="small "><i class="fas fa-angle-right"></i></div>
                    </div>
                </div>
            </div>
            <div class="col-xl-6 col-md-6">
                <div class="card mb-4">
                    <div class="card-body">Hotels</div>
                    <div class="card-footer d-flex align-items-center justify-content-between">
                        <a class="small stretched-link" href="{% url 'management:hotels' %}">Your hotels
                            - {{ hotels|length }}</a>
                        <div class="small"><i class="fas fa-angle-right"></i></div>
                    </div>
                </div>
            </div>
        </div>

        <div class="createHotel">
            <a href="{% url 'management:create_hotel' %}">
                Create Hotel <i class="fas fa-plus"></i>
            </a>
        </div>

        <div class="createHotel" style="right: 206px;">
            <a href="{% url 'management:create_room' %}">
                Create Room <i class="fas fa-plus"></i>
            </a>
        </div>

        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
        {% endfor %}

        {% endif %}

    </div>
</main>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
    $("#hotel").change(function () {
        let hotel_id = $(this).val();
        let rooms;

        console.log(hotel_id);

        $.ajax({
            url: '/management/ajax/get_rooms/',
            data: {
                'hotel': hotel_id,
            },
            dataType: 'json',
            success: function (data) {
                for (let room of data.rooms) {
                    $("#rooms").append(`<option value="${room.pk}">${room.name}</option>`)
                }
            },
            error: function () {
                alert('Unable to fetch data about rooms');
            }
        });
    });
</script>
<script>
    $(document).ready(function () {
        $('.createBookingBtn').click(function () {
            $('.createBookingForm').toggle();
        });
    });

</script>
<link href="{% static 'css/vanillajs-datepicker/dist/css/datepicker.min.css' %}" rel="stylesheet"/>
<!-- For Bootstrap 4 -->
<link href="{% static 'css/vanillajs-datepicker/dist/css/datepicker-bs4.min.css' %}" rel="stylesheet"/>
<!-- For Bulma -->
<link href="{% static 'css/vanillajs-datepicker/dist/css/datepicker-bulma.min.css' %}" rel="stylesheet"/>
<!-- For Foundation -->
<link href="{% static 'css/vanillajs-datepicker/dist/css/datepicker-foundation.min.css' %}" rel="stylesheet"/>

<script src="{% static 'css/vanillajs-datepicker/dist/js/datepicker.min.js' %}"></script>

<script src="{% static 'css/vanillajs-datepicker/dist/js/locales/fr.js' %}"></script>

<script src="{% static 'css/vanillajs-datepicker/dist/js/datepicker-full.min.js' %}"></script>
<script>
    const elem = document.getElementById('range');

    const dateRangePicker = new DateRangePicker(elem, {
        format: 'yyyy-mm-dd',
    });

</script>
<script>
    $(".formClose").click(function (e) {
        $('.createBookingForm').css({'display': 'none'});
    });
</script>
{% endblock %}

booking/adminapp/templates/adminapp/rooms.html
{% load static %}
{% load get_room_image %}
{% load truncate_text %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1;"/>
        <meta name="description" content=""/>
        <meta name="author" content=""/>
        <title>Dashboard - Book!</title>
        <link href="{% static 'css/admin/styles.css' %}" rel="stylesheet"/>
        <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
              crossorigin="anonymous"/>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    </head>
    <body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'management:main' %}">Book.com Admin</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i>
        </button><!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search"
                       aria-describedby="basic-addon2"/>
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Settings</a><a class="dropdown-item" href="#">Activity Log</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'auth:logout' %}">Logout</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        {% include 'adminapp/includes/nav.html' %}

        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    <div class="card mb-4">
                        <div class="card-header"><i class="fas fa-table mr-1"></i>Rooms</div>
                        <div class="card-body">
                            {% for room in rooms %}
                            <div class="list-item">
                                <p class="h3">
                                    {{room.name}}. ({{room.hotel.name}}).
                                    <a href="{% url 'management:edit_room' room.hotel.pk room.pk %}">
                                        <i class="fas fa-pencil-alt"></i>
                                    </a>
                                    <a href="{% url 'management:delete_room' room.pk %}">
                                        <i class="fa fa-trash" aria-hidden="true"></i>
                                    </a>
                                </p>
                                <img src="{{ room|get_room_image }}" alt="{{room.name}}">
                                <p class="h5">
                                    {{room.description|truncate_text}}
                                </p>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </main>

            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Book.com 2020</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
            crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'css/admin/chart-area-demo.js' %}"></script>
    <script src="{% static 'css/admin/chart-bar-demo.js' %}"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'css/admin/datatables-demo.js' %}"></script>
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"
            integrity="sha256-KM512VNnjElC30ehFwehXjx1YCHPiQkOPmqnrWtpccM=" crossorigin="anonymous"></script>


    </body>
</html>